-- Customer Lifetime Value & RFM — RFM scoring and segmentation
--
-- Computes recency, frequency and monetary value per customer, scores each metric into
-- quartiles with APPROX_QUANTILES, and applies rule-based logic to assign one of seven
-- segments: Best Customers, Loyal Customers, Big Spenders, Promotion-Driven, At-Risk,
-- One-Time Purchasers, Lost Customers.
--
-- Source: `tc-da-1.turing_data_analytics.rfm` (BigQuery)
-- Scope: invoices from 2010-12-01 to 2011-12-02, excluding null CustomerID and
--        non-positive Quantity / UnitPrice.

-- TODO: paste your query from BigQuery here.
-- (BigQuery console -> Personal history / Project history -> copy the query text.)
